GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoiQWxiZXJ0IExlb25hcmRpIiwiZW1haWwiOiJsZW9nYXRzdW1hQGdtYWlsLmNvbSIsImlhdCI6MTcxNjk5NzA3NywiZXhwIjoxNzE2OTk3MTk3fQ.htBozFiMxbyY5b4FG7rYKKxyhWeiK9Pf_lzutm1B8Rg
###
POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "Haibeb",
    "email": "hai@gmail.com",
    "password": "1234569",
    "confPassword": "1234569"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "Albert Leonardi",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "Latief",
    "email": "latief@gmail.com",
    "password": "0987654321",
    "confPassword": "0987654321"
}

###
POST http://localhost:5000/addcourse
Content-Type: application/json

{
    "name": "Frieren Keren",
    "teacherId": "1",
    "category": "Mobile-Dev",
    "rating": "4.5",
    "price": "2000000"
}

###
GET http://localhost:5000/courses

###
POST http://localhost:5000/addcoursedetail
Content-Type: application/json

{
    "courseId": "1",
    "desc": "Ini buat belajar tentang kehidupan",
    "duration": "40",
    "learning_outcomes": "Laravel, Web-Dev, API",
    "modules": "41",
    "students": "2000",
    "language": "Indonesia"
}

###
GET http://localhost:5000/course-details/1